### ISSUE TITLE
Problemas com versão 1.3.1 do Spree -  uninitialized constant Spree::ThemeSupport (NameError)

### ISSUE THREAD

**Issue by ronaldocpontes** [thitemple/spree-correios-shipping#6]
Olá,

Estou tendo o seguinte problema quando adiciono gem e inicio com "rails s":

spree_correios_shipping_hooks.rb:1:in
`<top (required)>': uninitialized constant Spree::ThemeSupport (NameError)

Sabe como posso resolver?

Abs,
Ronaldo

Ai vai o full stack:

C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/bundler/gems/spree-correios-shipping-dab603de2d4f/lib/spree_correios_shipping_hooks.rb:1:in
`<top (required)>': uninitialized constant Spree::ThemeSupport (NameError)
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/polyglot-0.3.3/lib/polyglot.rb:63:in`require'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/polyglot-0.3.3/lib/polyglot.rb:63:in `require'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/bundler/gems/spree-correios-shipping-dab603de2d4f/lib/spree_correios_shipping.r
b:2:in`<top (required)>'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in `require'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler/runtime.rb:68:in`block (2 levels) in require'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in `each'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler/runtime.rb:66:in`block in require'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in `each'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler/runtime.rb:55:in`require'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/bundler-1.2.3/lib/bundler.rb:128:in `require'
        from C:/RailsInstaller/workspace/store/config/application.rb:7:in`<top (required)>'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/railties-3.2.11/lib/rails/commands.rb:53:in `require'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/railties-3.2.11/lib/rails/commands.rb:53:in`block in <top (required)>'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/railties-3.2.11/lib/rails/commands.rb:50:in `tap'
        from C:/RailsInstaller/Ruby1.9.2/lib/ruby/gems/1.9.1/gems/railties-3.2.11/lib/rails/commands.rb:50:in`<top (required)>'
        from script/rails:6:in `require'
        from script/rails:6:in`<main>'

**Comment by thitemple** [comment]
Olá Ronaldo, eu fiz isso para um projeto que precisei e usei a ver 0.4 do Spree, depois disso nunca mais alterei. Fique a vontade para fazer as modificações necessárias.

**Comment by ronaldocpontes** [comment]
Ok Thiago,

Obrigado pelo retorno

Abs,
Ronaldo

2013/1/21 Thiago Temple notifications@github.com
